on:
  push:
    branches:
      - master
      - develop

env:
  version: 13.0

jobs:
  build:
    strategy:
      matrix:
        platform: ['OS', 'SIMULATOR']

    name: iOS ${{ matrix.platform }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Apply patch
        run: |
          cd 3rdparty/tensorflow && git apply ../../fix.patch

      - name: Build
        run: |
          cmake -DCMAKE_TOOLCHAIN_FILE=./cmake/modules/iOS.cmake -DIOS_PLATFORM=${{ matrix.platform }} -DIOS_DEPLOYMENT_TARGET=${{ env.version }} -H. -Bbuild -GXcode
          cmake --build build --config Release -j2

      - name: Upload
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: iOS-${{ matrix.platform }}
          path: build/lib/Release/

  pack:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: actions/download-artifact@v4
        with:
          path: intermediate/lib
          pattern: 'iOS-*'

      - run: |
          mkdir -p build/include
          cp -r include build/include

      - name: Merge libraries
        run: |
          mkdir build/lib
          libtool -static -o build/lib/libtfcv.a intermediate/lib/**/*.a

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: iOS
          path: build/