on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - release/*
  workflow_dispatch:

env:
  ios-version: 13.0

jobs:
  # Android build job
  ####################
  build-android:
    strategy:
      fail-fast: false
      matrix:
        arch: ['arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64']
    name: Android ${{ matrix.arch }}
    runs-on: ubuntu-latest
    outputs:
      artifact-id: ${{ steps.upload.outputs.artifact_id }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Apply patch
        run: |
          cd 3rdparty/tensorflow && git apply ../../fix.patch

      - name: Build
        run: |
          cmake -DCMAKE_TOOLCHAIN_FILE="$ANDROID_HOME"/ndk/25.2.9519653/build/cmake/android.toolchain.cmake \
                -DANDROID_ABI="${{ matrix.arch }}" \
                -DANDROID_PLATFORM=android-26 \
                -S. \
                -Bbuild \
                -DBUILD_SHARED_LIBS=ON \
                $(test "${{ matrix.arch }}" = "armeabi-v7a" && echo "-DTFLITE_ENABLE_XNNPACK=OFF")
          
          cmake --build build --config Release -j4
          cmake --install build --prefix out

      - name: Upload
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: Android-${{ matrix.arch }}
          path: out/**/*

  # iOS build job
  #################
  build-ios:
    strategy:
      matrix:
        platform: [ 'OS', 'SIMULATOR' ]

    name: iOS ${{ matrix.platform }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Apply patch
        run: |
          cd 3rdparty/tensorflow && git apply ../../fix.patch

      - name: Build
        run: |
          cmake -DCMAKE_TOOLCHAIN_FILE=./cmake/modules/iOS.cmake \
                -DIOS_PLATFORM=${{ matrix.platform }} \
                -DIOS_DEPLOYMENT_TARGET=${{ env.ios-version }} \
                -H. \
                -Bbuild \
                -GXcode
          
          cmake --build build --config Release -j3
          cmake --install build --prefix out
          
          # Make sure libtfcv.a contains all its dependencies
          libtool -static -o out/lib/libtfcv.a $(find build/ -name '*.a')

      - name: Upload
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: iOS-${{ matrix.platform }}
          path: out/**/*

  # Create artifact from partial builds
  ######################################
  pack:
    needs: [build-ios]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # Download iOS artifacts
      - uses: actions/download-artifact@v4
        with:
          path: intermediate/lib
          pattern: 'iOS-*'

      - name: Merge iOS Os & Simulator libraries
        run: |
          mkdir -p build/lib/
          cp -r intermediate/lib/iOS-OS/include build/include
          for fn in $(ls -a intermediate/lib/iOS-OS/lib | grep "\.a"); do 
            lipo -create intermediate/lib/iOS-OS/lib/$fn intermediate/lib/iOS-SIMULATOR/lib/$fn -output build/lib/$fn
          done

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Multiplatform
          path: build/

#  pack-android:
#    needs: [build-android]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          submodules: 'recursive'
#
#      # Download Android artifacts
#      - uses: actions/download-artifact@v4
#        with:
#          path: build/lib
#          pattern: 'Android-*'
#          merge-multiple: true