on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Apply patch
      run: |
        cd 3rdparty/tensorflow && git apply ../../fix.patch

    - name: Build
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd ${{ github.workspace }}
        bin/build-android.sh

    - name: Build
      if: matrix.os == 'macos-latest'
      run: |
        cd ${{ github.workspace }}
        bin/build-ios.sh

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-${{ github.run_number }}
        path: lib/