on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - release/*
  workflow_dispatch:

env:
  ios-version: 13.0

jobs:
  # iOS build job
  #################
  build-ios:
    strategy:
      matrix:
        platform: [ 'OS', 'SIMULATOR' ]

    name: iOS ${{ matrix.platform }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Apply patch
        run: |
          cd 3rdparty/tensorflow && git apply ../../fix.patch

      - name: Build
        run: |
          cmake -DCMAKE_TOOLCHAIN_FILE=./cmake/modules/iOS.cmake \
                -DIOS_PLATFORM=${{ matrix.platform }} \
                -DIOS_DEPLOYMENT_TARGET=${{ env.ios-version }} \
                -H. \
                -Bbuild \
                -GXcode
          
          cmake --build build --config Release -j3
          cmake --install build --prefix out
          
          # Merge everything into a single static library
          rm -rf out/lib/*
          libtool -static -o out/lib/libtfcv.a $(find build/ -name '*.a')

      - name: Upload
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: iOS-${{ matrix.platform }}
          path: out/**/*

  # Create artifact from partial builds
  ######################################
  pack:
    needs: [build-ios]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # Download iOS artifacts
      - uses: actions/download-artifact@v4
        with:
          path: intermediate/lib
          pattern: 'iOS-*'

      - name: Merge iOS Os & Simulator libraries
        run: |
          mkdir -p build/lib/
          cp -r intermediate/lib/iOS-OS/include build/include
          for fn in $(ls -a intermediate/lib/iOS-OS/lib | grep "\.a"); do 
            lipo -create intermediate/lib/iOS-OS/lib/$fn intermediate/lib/iOS-SIMULATOR/lib/$fn -output build/lib/$fn
          done

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: iOS-Multitarget
          path: build/

  createMavenArtifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Apply patch
        run: |
          cd 3rdparty/tensorflow && git apply ../../fix.patch

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y ninja-build

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.30.3'

      - name: Assemble
        run: |
          bin/assembleAndroidPackage.sh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Android-Maven
          path: platform/android/tfcv/build/outputs/aar/tfcv-release.aar